### ISSUE TITLE
[질문의 예시] 텐서플로우와 openAI gym 설치 시 오류 

### ISSUE THREAD

**Issue by unizard** [moduPlayGround/DeepLearning-Basic#8]
안녕하세요  김해린 입니다. 
강의에서 텐서플로우와 openAI gym을 설치하는데 질문사항이 있어 메일드립니다. 

anaconda prompt창에서 (python에서)
import tensorflow와 import gym을 입력하면 아무문제가 없다고 나옵니다. 
하지만 atari에서 오류가 나는데요, 제 노트북이 윈도우체제라 윈도우에서 make 명령을 하기 위한 파일도 구글링 하여 다운로드 했으나 이런식으로 에러가 뜹니다 ㅠㅠ
아직 운영체제나 텐서플로우를 배워본적이 없어서 모르는게 많은데 여기서 어떻게 해야할지 모르겠습니다 ㅠㅠ

![image](https://user-images.githubusercontent.com/11758940/48069516-0920bb80-e219-11e8-9ad5-66d3f6e8dc7d.png)

**Comment by unizard** [comment]
@김해린 

김해린양, 모놀 1기 강의 시작은 Reinforce Learning 이 아니라, 딥러닝 기본입니다. ^^
기본 먼저 합시다. ㅋ

**Comment by lini1634** [comment]
저부분이 처음 시작인줄알았네요 ㅋㅋㅋㅋ 죄송합니당
