### ISSUE TITLE
[공지] 스터디 1주차 모임 공지

### ISSUE THREAD

**Issue by unizard** [moduPlayGround/DeepLearning-Basic#9]
![image](https://user-images.githubusercontent.com/11758940/48071118-d4aefe80-e21c-11e8-9dde-6493b61426cd.png)

- 자신이 맡은 부분만 공부하는게 아닙니다. 반드시! 모두 동영상을 시청하고 실습까지 스스로 해봅니다.
- 모임 당일날 각자 자신이 맡은 부분을 주도적으로 리뷰합니다.
- 발표형식은 자유입니다만, 타인을 설득시키고 연습하는 것 역시 중요한 역량이므로 노력해봅시다.
- 발표자료의 화려함보다, 컨텐츠에 집중합시다.
- 담당한 섹션과 관련된 모든 질의 응답은 담당학생이 주도적으로 답하고 해결하나, 모놀 모두가 함께 노력합시다.
- 상대를 배려하고 도와주는 모습의 결과는 스터디가 마무리 될 때 쯤 어떤 형태로든 보상* 이 있을 겁니다.  😘
- 혹시, 개인 컴퓨터에  tensorflow를 설치하는 번거로움을 피하고 싶은 학생은 colab을 활용하셔도 좋습니다. (https://www.youtube.com/watch?v=Y9MqoK5tUkw&feature=youtu.be&app=desktop)

**Comment by unizard** [comment]
본 이슈의 코멘트에 아래와 같이 각자의 온라인 강의 및 실습 진행 상황을 공유해주세요.

## 온라인 강의 및 실습 진행 상황
- [X] Lecture0: 수업의 개요와 일정
- [ ] Lecture1: Tensorflow 설치 및 기본적인 Operations
- [ ] Lecture2: Linear Regression의 Hypothesis 와 Cost 설명 
- [ ] Lecture2-Lab: Tensorflow 실습
- [ ] Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명 
- [ ] Lecture3-Lab: Tensorflow 실습
- [ ] Lecture4: Multi-variable linear regression 
- [ ] Lecture4-Lab: Tensorflow 실습

**Comment by socome** [comment]
## 온라인 강의 및 실습 진행 상황
- [X] Lecture0: 수업의 개요와 일정
- [X] Lecture1: Tensorflow 설치 및 기본적인 Operations
- [X] Lecture2: Linear Regression의 Hypothesis 와 Cost 설명 
- [X] Lecture2-Lab: Tensorflow 실습
- [X] Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명 
- [X] Lecture3-Lab: Tensorflow 실습
- [X] Lecture4: Multi-variable linear regression 
- [ ] Lecture4-Lab: Tensorflow 실습

**Comment by hyj378** [comment]
> 본 이슈의 코멘트에 아래와 같이 각자의 온라인 강의 및 실습 진행 상황을 공유해주세요.
> 진행상황을 통해 현재 설정되어있는 학습량을 조율할 수 있습니다.
> (여러분이 힘들어하면 줄여야겠죠?)
> Edit 누르시고 아래의 MD 소스 복사해서 사용하세요.
> 
> ## 온라인 강의 및 실습 진행 상황
> * [x]  Lecture0: 수업의 개요와 일정
> * [x]  Lecture1: Tensorflow 설치 및 기본적인 Operations
> * [x]  Lecture2: Linear Regression의 Hypothesis 와 Cost 설명
> * [x]  Lecture2-Lab: Tensorflow 실습
> * [ ]  Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명
> * [ ]  Lecture3-Lab: Tensorflow 실습
> * [ ]  Lecture4: Multi-variable linear regression
> * [ ]  Lecture4-Lab: Tensorflow 실습

**Comment by pk000983** [comment]
> ## 온라인 강의 및 실습 진행 상황
> * [x]  Lecture0: 수업의 개요와 일정
> * [x]  Lecture1: Tensorflow 설치 및 기본적인 Operations
> * [x]  Lecture2: Linear Regression의 Hypothesis 와 Cost 설명
> * [x]  Lecture2-Lab: Tensorflow 실습
> * [x]  Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명
> * [x]  Lecture3-Lab: Tensorflow 실습
> * [x]  Lecture4: Multi-variable linear regression
> * [x]  Lecture4-Lab: Tensorflow 실습

**Comment by sejongleejeongmin** [comment]
> ## 온라인 강의 및 실습 진행 상황
> * [x]  Lecture0: 수업의 개요와 일정
> * [x]  Lecture1: Tensorflow 설치 및 기본적인 Operations
> * [x]  Lecture2: Linear Regression의 Hypothesis 와 Cost 설명
> * [x]  Lecture2-Lab: Tensorflow 실습
> * [x]  Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명
> * [x]  Lecture3-Lab: Tensorflow 실습
> * [ ]  Lecture4: Multi-variable linear regression
> * [ ]  Lecture4-Lab: Tensorflow 실습

**Comment by kmj0249** [comment]
> 본 이슈의 코멘트에 아래와 같이 각자의 온라인 강의 및 실습 진행 상황을 공유해주세요.
> 진행상황을 통해 현재 설정되어있는 학습량을 조율할 수 있습니다.
> (여러분이 힘들어하면 줄여야겠죠?)
> Edit 누르시고 아래의 MD 소스 복사해서 사용하세요.
> 
> ## 온라인 강의 및 실습 진행 상황
> * [o]  Lecture0: 수업의 개요와 일정
> * [o]  Lecture1: Tensorflow 설치 및 기본적인 Operations
> * [o]  Lecture2: Linear Regression의 Hypothesis 와 Cost 설명
> * [o]  Lecture2-Lab: Tensorflow 실습
> * [o]  Lecture3: Linear Regression의 Cost 최소화 알고리즘 원리 설명
> * [o]  Lecture3-Lab: Tensorflow 실습
> * [o]  Lecture4: Multi-variable linear regression
> * [o]  Lecture4-Lab: Tensorflow 실습
